/* ─────────────────────────────────────────────────────────────────────────
   HELPERS
───────────────────────────────────────────────────────────────────────── */
const INR = (n) => "₹" + Number(n).toLocaleString("en-IN");
const WA_NUMBER = "917304607954";
const GST_RATE = 0.18;

const CITIES = [
  "Mumbai",
  "Delhi NCR",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Other",
];

/* ─────────────────────────────────────────────────────────────────────────
   CURRENCIES
───────────────────────────────────────────────────────────────────────── */
const CURRENCIES = [
  {
    code: "USD",
    name: "US Dollar",
    flag: "🇺🇸",
    symbol: "$",
    country: "United States",
  },
  {
    code: "GBP",
    name: "British Pound",
    flag: "🇬🇧",
    symbol: "£",
    country: "United Kingdom",
  },
  {
    code: "THB",
    name: "Thai Baht",
    flag: "🇹🇭",
    symbol: "฿",
    country: "Thailand",
  },
  {
    code: "AED",
    name: "UAE Dirham",
    flag: "🇦🇪",
    symbol: "AED ",
    country: "United Arab Emirates",
  },
  {
    code: "EUR",
    name: "Euro",
    flag: "🇪🇺",
    symbol: "€",
    country: "European Union",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    flag: "🇦🇺",
    symbol: "A$",
    country: "Australia",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    flag: "🇨🇳",
    symbol: "¥",
    country: "China",
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    flag: "🇱🇰",
    symbol: "LKR ",
    country: "Sri Lanka",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    flag: "🇲🇾",
    symbol: "MYR ",
    country: "Malaysia",
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    flag: "🇻🇳",
    symbol: "₫",
    country: "Vietnam",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    flag: "🇸🇬",
    symbol: "S$",
    country: "Singapore",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    flag: "🇸🇦",
    symbol: "SAR ",
    country: "Saudi Arabia",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    flag: "🇿🇦",
    symbol: "ZAR ",
    country: "South Africa",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    flag: "🇨🇭",
    symbol: "Fr ",
    country: "Switzerland",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    flag: "🇨🇦",
    symbol: "C$",
    country: "Canada",
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    flag: "🇳🇵",
    symbol: "NPR ",
    country: "Nepal",
  },
  {
    code: "OMR",
    name: "Omani Rial",
    flag: "🇴🇲",
    symbol: "OMR ",
    country: "Oman",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    flag: "🇭🇰",
    symbol: "HK$",
    country: "Hong Kong",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    flag: "🇧🇩",
    symbol: "৳",
    country: "Bangladesh",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    flag: "🇯🇵",
    symbol: "¥",
    country: "Japan",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    flag: "🇸🇪",
    symbol: "SEK ",
    country: "Sweden",
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    flag: "🇶🇦",
    symbol: "QAR ",
    country: "Qatar",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    flag: "🇳🇿",
    symbol: "NZ$",
    country: "New Zealand",
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    flag: "🇮🇱",
    symbol: "₪",
    country: "Israel",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    flag: "🇰🇼",
    symbol: "KWD ",
    country: "Kuwait",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    flag: "🇧🇭",
    symbol: "BHD ",
    country: "Bahrain",
  },
  {
    code: "DKK",
    name: "Danish Krone",
    flag: "🇩🇰",
    symbol: "kr ",
    country: "Denmark",
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    flag: "🇰🇪",
    symbol: "KES ",
    country: "Kenya",
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    flag: "🇲🇺",
    symbol: "MUR ",
    country: "Mauritius",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    flag: "🇳🇴",
    symbol: "NOK ",
    country: "Norway",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    flag: "🇵🇭",
    symbol: "₱",
    country: "Philippines",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    flag: "🇷🇺",
    symbol: "₽",
    country: "Russia",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    flag: "🇦🇫",
    symbol: "؋",
    country: "Afghanistan",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    flag: "🇦🇱",
    symbol: "L ",
    country: "Albania",
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    flag: "🇩🇿",
    symbol: "DZD ",
    country: "Algeria",
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    flag: "🇦🇴",
    symbol: "Kz ",
    country: "Angola",
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    flag: "🌴",
    symbol: "EC$",
    country: "East Caribbean",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    flag: "🇦🇷",
    symbol: "$",
    country: "Argentina",
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    flag: "🇦🇲",
    symbol: "AMD ",
    country: "Armenia",
  },
  {
    code: "AWG",
    name: "Aruban Florin",
    flag: "🇦🇼",
    symbol: "ƒ",
    country: "Aruba",
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    flag: "🇦🇿",
    symbol: "₼",
    country: "Azerbaijan",
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    flag: "🇧🇸",
    symbol: "$",
    country: "Bahamas",
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    flag: "🇧🇧",
    symbol: "$",
    country: "Barbados",
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    flag: "🇧🇿",
    symbol: "BZ$",
    country: "Belize",
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    flag: "🌍",
    symbol: "XOF ",
    country: "West Africa",
  },
  {
    code: "BMD",
    name: "Bermudian Dollar",
    flag: "🇧🇲",
    symbol: "$",
    country: "Bermuda",
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    flag: "🇧🇹",
    symbol: "Nu ",
    country: "Bhutan",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    flag: "🇧🇴",
    symbol: "Bs ",
    country: "Bolivia",
  },
  {
    code: "BWP",
    name: "Botswana Pula",
    flag: "🇧🇼",
    symbol: "P ",
    country: "Botswana",
  },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Mark",
    flag: "🇧🇦",
    symbol: "KM ",
    country: "Bosnia & Herzegovina",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    flag: "🇧🇷",
    symbol: "R$",
    country: "Brazil",
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    flag: "🇧🇳",
    symbol: "$",
    country: "Brunei",
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    flag: "🇧🇬",
    symbol: "лв ",
    country: "Bulgaria",
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    flag: "🇧🇮",
    symbol: "Fr ",
    country: "Burundi",
  },
  {
    code: "KHR",
    name: "Cambodian Riel",
    flag: "🇰🇭",
    symbol: "៛",
    country: "Cambodia",
  },
  {
    code: "XAF",
    name: "Central African CFA",
    flag: "🌍",
    symbol: "XAF ",
    country: "Central Africa",
  },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    flag: "🇨🇻",
    symbol: "$",
    country: "Cape Verde",
  },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    flag: "🇰🇾",
    symbol: "$",
    country: "Cayman Islands",
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    flag: "🇨🇱",
    symbol: "$",
    country: "Chile",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    flag: "🇨🇴",
    symbol: "$",
    country: "Colombia",
  },
  {
    code: "KMF",
    name: "Comorian Franc",
    flag: "🇰🇲",
    symbol: "Fr ",
    country: "Comoros",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    flag: "🇨🇷",
    symbol: "₡",
    country: "Costa Rica",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    flag: "🇨🇿",
    symbol: "Kč ",
    country: "Czech Republic",
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    flag: "🇨🇩",
    symbol: "Fr ",
    country: "DR Congo",
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    flag: "🇩🇯",
    symbol: "Fr ",
    country: "Djibouti",
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    flag: "🇩🇴",
    symbol: "$",
    country: "Dominican Republic",
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    flag: "🇪🇬",
    symbol: "£",
    country: "Egypt",
  },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    flag: "🇪🇷",
    symbol: "Nfk ",
    country: "Eritrea",
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    flag: "🇪🇹",
    symbol: "Br ",
    country: "Ethiopia",
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    flag: "🇫🇯",
    symbol: "$",
    country: "Fiji",
  },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    flag: "🇫🇰",
    symbol: "£",
    country: "Falkland Islands",
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    flag: "🇬🇲",
    symbol: "D ",
    country: "Gambia",
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    flag: "🇬🇪",
    symbol: "₾",
    country: "Georgia",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    flag: "🇬🇭",
    symbol: "GH₵",
    country: "Ghana",
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    flag: "🇬🇮",
    symbol: "£",
    country: "Gibraltar",
  },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    flag: "🇬🇹",
    symbol: "Q ",
    country: "Guatemala",
  },
  {
    code: "GNF",
    name: "Guinean Franc",
    flag: "🇬🇳",
    symbol: "Fr ",
    country: "Guinea",
  },
  {
    code: "GYD",
    name: "Guyanese Dollar",
    flag: "🇬🇾",
    symbol: "$",
    country: "Guyana",
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    flag: "🇭🇹",
    symbol: "G ",
    country: "Haiti",
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    flag: "🇭🇳",
    symbol: "L ",
    country: "Honduras",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    flag: "🇭🇺",
    symbol: "Ft ",
    country: "Hungary",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    flag: "🇮🇸",
    symbol: "kr ",
    country: "Iceland",
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    flag: "🇮🇩",
    symbol: "Rp ",
    country: "Indonesia",
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    flag: "🇮🇶",
    symbol: "IQD ",
    country: "Iraq",
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    flag: "🇯🇲",
    symbol: "$",
    country: "Jamaica",
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    flag: "🇯🇴",
    symbol: "JOD ",
    country: "Jordan",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    flag: "🇰🇿",
    symbol: "₸",
    country: "Kazakhstan",
  },
  {
    code: "KGS",
    name: "Kyrgyzstani Som",
    flag: "🇰🇬",
    symbol: "с ",
    country: "Kyrgyzstan",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    flag: "🇰🇷",
    symbol: "₩",
    country: "South Korea",
  },
  { code: "LAK", name: "Lao Kip", flag: "🇱🇦", symbol: "₭", country: "Laos" },
  {
    code: "LBP",
    name: "Lebanese Pound",
    flag: "🇱🇧",
    symbol: "LBP ",
    country: "Lebanon",
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    flag: "🇱🇷",
    symbol: "$",
    country: "Liberia",
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    flag: "🇱🇾",
    symbol: "LYD ",
    country: "Libya",
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    flag: "🇲🇦",
    symbol: "MAD ",
    country: "Morocco",
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    flag: "🇲🇩",
    symbol: "L ",
    country: "Moldova",
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    flag: "🇲🇬",
    symbol: "Ar ",
    country: "Madagascar",
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    flag: "🇲🇰",
    symbol: "den ",
    country: "North Macedonia",
  },
  {
    code: "MNT",
    name: "Mongolian Tögrög",
    flag: "🇲🇳",
    symbol: "₮",
    country: "Mongolia",
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    flag: "🇲🇴",
    symbol: "P ",
    country: "Macau",
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    flag: "🇲🇷",
    symbol: "UM ",
    country: "Mauritania",
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    flag: "🇲🇻",
    symbol: "Rf ",
    country: "Maldives",
  },
  {
    code: "MWK",
    name: "Malawian Kwacha",
    flag: "🇲🇼",
    symbol: "MK ",
    country: "Malawi",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    flag: "🇲🇽",
    symbol: "$",
    country: "Mexico",
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    flag: "🇲🇿",
    symbol: "MT ",
    country: "Mozambique",
  },
  {
    code: "NAD",
    name: "Namibian Dollar",
    flag: "🇳🇦",
    symbol: "$",
    country: "Namibia",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    flag: "🇳🇬",
    symbol: "₦",
    country: "Nigeria",
  },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    flag: "🇳🇮",
    symbol: "C$",
    country: "Nicaragua",
  },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    flag: "🇵🇬",
    symbol: "K ",
    country: "Papua New Guinea",
  },
  {
    code: "PYG",
    name: "Paraguayan Guaraní",
    flag: "🇵🇾",
    symbol: "₲",
    country: "Paraguay",
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    flag: "🇵🇪",
    symbol: "S/",
    country: "Peru",
  },
  {
    code: "PLN",
    name: "Polish Złoty",
    flag: "🇵🇱",
    symbol: "zł ",
    country: "Poland",
  },
  {
    code: "RON",
    name: "Romanian Leu",
    flag: "🇷🇴",
    symbol: "lei ",
    country: "Romania",
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    flag: "🇷🇸",
    symbol: "din ",
    country: "Serbia",
  },
  {
    code: "RWF",
    name: "Rwandan Franc",
    flag: "🇷🇼",
    symbol: "Fr ",
    country: "Rwanda",
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    flag: "🇸🇧",
    symbol: "$",
    country: "Solomon Islands",
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    flag: "🇸🇨",
    symbol: "SR ",
    country: "Seychelles",
  },
  {
    code: "SHP",
    name: "Saint Helena Pound",
    flag: "🇸🇭",
    symbol: "£",
    country: "Saint Helena",
  },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    flag: "🇸🇱",
    symbol: "Le ",
    country: "Sierra Leone",
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    flag: "🇸🇴",
    symbol: "Sh ",
    country: "Somalia",
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    flag: "🇸🇷",
    symbol: "$",
    country: "Suriname",
  },
  {
    code: "SZL",
    name: "Swazi Lilangeni",
    flag: "🇸🇿",
    symbol: "L ",
    country: "Eswatini",
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    flag: "🇹🇯",
    symbol: "SM ",
    country: "Tajikistan",
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    flag: "🇹🇲",
    symbol: "T ",
    country: "Turkmenistan",
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    flag: "🇹🇳",
    symbol: "TND ",
    country: "Tunisia",
  },
  {
    code: "TOP",
    name: "Tongan Paʻanga",
    flag: "🇹🇴",
    symbol: "T$",
    country: "Tonga",
  },
  {
    code: "TTD",
    name: "Trinidad & Tobago Dollar",
    flag: "🇹🇹",
    symbol: "$",
    country: "Trinidad & Tobago",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    flag: "🇹🇷",
    symbol: "₺",
    country: "Turkey",
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    flag: "🇹🇼",
    symbol: "NT$",
    country: "Taiwan",
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    flag: "🇹🇿",
    symbol: "Sh ",
    country: "Tanzania",
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    flag: "🇺🇦",
    symbol: "₴",
    country: "Ukraine",
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    flag: "🇺🇬",
    symbol: "Sh ",
    country: "Uganda",
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    flag: "🇺🇾",
    symbol: "$",
    country: "Uruguay",
  },
  {
    code: "UZS",
    name: "Uzbekistani Som",
    flag: "🇺🇿",
    symbol: "UZS ",
    country: "Uzbekistan",
  },
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    flag: "🇻🇺",
    symbol: "Vt ",
    country: "Vanuatu",
  },
  {
    code: "WST",
    name: "Samoan Tālā",
    flag: "🇼🇸",
    symbol: "T ",
    country: "Samoa",
  },
  {
    code: "XPF",
    name: "CFP Franc",
    flag: "🇵🇫",
    symbol: "Fr ",
    country: "French Polynesia",
  },
  {
    code: "YER",
    name: "Yemeni Rial",
    flag: "🇾🇪",
    symbol: "YER ",
    country: "Yemen",
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    flag: "🇿🇲",
    symbol: "ZK ",
    country: "Zambia",
  },
];

const ZERO_DECIMAL = new Set([
  "JPY",
  "KRW",
  "IDR",
  "VND",
  "BIF",
  "CLP",
  "DJF",
  "GNF",
  "ISK",
  "KMF",
  "MGA",
  "PYG",
  "RWF",
  "UGX",
  "VUV",
  "XAF",
  "XOF",
  "XPF",
]);
const THREE_DECIMAL = new Set([
  "KWD",
  "BHD",
  "OMR",
  "JOD",
  "TND",
  "IQD",
  "LYD",
]);

export {
  INR,
  WA_NUMBER,
  GST_RATE,
  CITIES,
  CURRENCIES,
  ZERO_DECIMAL,
  THREE_DECIMAL,
};
